version: '3'
services:
  streamlit-food-readouts:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit-food-readouts
    volumes:
      - ./logs:/app/logs:rw
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: foodreadouts.gnps2.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: foodreadouts.gnps2.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com

networks:
  nginx-net:
    external:
      name: nginx-net